export const mockData = {
  kpis: {
    customers: 3781,
    customersChangePct: 11.01,
    orders: 1219,
    ordersChangePct: -0.03,
    revenueTotal: 695,
    revenueChangePct: 15.03,
    growthPct: 30.1,
    growthChangePct: 6.08,
  },

  revenues: {
    labels: ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    datasets: [
      {
        label: "Actuals",
        data: [8, 17, 15, 10, 16, 23],
        borderColor: "#A9CCE3",
        tension: 0.4,
        fill: false,
      },
      {
        label: "Forecast (Solid)",
        data: [12, 8, 9, 15, null, null],
        borderColor: "#17202A",
        tension: 0.4,
        fill: false,
      },
      {
        label: "Forecast (Dashed)",
        data: [null, null, null, 15, 19, 20],
        borderColor: "#17202A",
        borderDash: [5, 5],
        tension: 0.4,
        fill: false,
      },
    ],
  },

  monthly: [
    {
      month: "Jan",
      revenue: 12000000,
      projection: 15000000,
    },
    {
      month: "Feb",
      revenue: 18000000,
      projection: 20000000,
    },
    {
      month: "Mar",
      revenue: 16000000,
      projection: 17000000,
    },
    {
      month: "Apr",
      revenue: 22000000,
      projection: 25000000,
    },
    {
      month: "May",
      revenue: 14000000,
      projection: 16000000,
    },
    {
      month: "Jun",
      revenue: 21000000,
      projection: 23000000,
    },
  ],

  topProducts: [
    {
      name: "ASOS Ridley High Waist",
      price: 79.49,
      quantity: 82,
      amount: 6518.18,
    },
    {
      name: "Marco Lightweight Shirt",
      price: 128.5,
      quantity: 37,
      amount: 4754.5,
    },
    { name: "Half Sleeve Shirt", price: 39.99, quantity: 64, amount: 2559.36 },
    { name: "Lightweight Jacket", price: 20.0, quantity: 184, amount: 3680.0 },
    { name: "Marco Shoes", price: 79.49, quantity: 24, amount: 1907.76 },
  ],

  revenueByLocation: [
    { name: "New York", revenue: 72000, left: "15%", top: "36%" },
    { name: "San Francisco", revenue: 39000, left: "28%", top: "42%" },
    { name: "Sydney", revenue: 25000, left: "84%", top: "77%" },
    { name: "Singapore", revenue: 61000, left: "73%", top: "58%" },
  ],

  salesChannels: [
    { channel: "Direct", amount: 300.56 },
    { channel: "Affiliate", amount: 135.18 },
    { channel: "Sponsored", amount: 154.02 },
    { channel: "E-mail", amount: 48.96 },
  ],

  orders: [
    {
      orderId: "CM9801",
      user: {
        name: "Natali Craig",
        avatarUrl: "https://example.com/avatars/natalicraig.jpg",
      },
      project: "Landing Page",
      address: "Meadow Lane Oakland",
      date: "Just now",
      status: "In Progress",
    },
    {
      orderId: "CM9802",
      user: {
        name: "Kate Morrison",
        avatarUrl: "https://example.com/avatars/katemorrison.jpg",
      },
      project: "CRM Admin pages",
      address: "Larry San Francisco",
      date: "A minute ago",
      status: "Complete",
    },
    {
      orderId: "CM9803",
      user: {
        name: "Drew Cano",
        avatarUrl: "https://example.com/avatars/drewcano.jpg",
      },
      project: "Client Project",
      address: "Bagwell Avenue Ocala",
      date: "1 hour ago",
      status: "Pending",
    },
    {
      orderId: "CM9804",
      user: {
        name: "Orlando Diggs",
        avatarUrl: "https://example.com/avatars/orlandodiggs.jpg",
      },
      project: "Admin Dashboard",
      address: "Washburn Baton Rouge",
      date: "Yesterday",
      status: "Approved",
    },
    {
      orderId: "CM9805",
      user: {
        name: "Andi Lane",
        avatarUrl: "https://example.com/avatars/andilane.jpg",
      },
      project: "App Landing Page",
      address: "Nest Lane Olivette",
      date: "Feb 2, 2023",
      status: "Rejected",
    },
    {
      orderId: "CM9806",
      user: {
        name: "Jesse Smith",
        avatarUrl: "https://example.com/avatars/jessesmith.jpg",
      },
      project: "E-commerce Website",
      address: "123 Main St, Anytown",
      date: "3 hours ago",
      status: "In Progress",
    },
    {
      orderId: "CM9807",
      user: {
        name: "Taylor Jones",
        avatarUrl: "https://example.com/avatars/taylorjones.jpg",
      },
      project: "Blog Content",
      address: "456 Oak Ave, Somewhere",
      date: "5 hours ago",
      status: "Complete",
    },
    {
      orderId: "CM9808",
      user: {
        name: "Alex Miller",
        avatarUrl: "https://example.com/avatars/alexmiller.jpg",
      },
      project: "Mobile App UI/UX",
      address: "789 Pine Ln, Nowhere",
      date: "Yesterday",
      status: "Pending",
    },
    {
      orderId: "CM9809",
      user: {
        name: "Chris Davis",
        avatarUrl: "https://example.com/avatars/chrisdavis.jpg",
      },
      project: "Logo Design",
      address: "101 Maple Rd, Aplace",
      date: "2 days ago",
      status: "Approved",
    },
    {
      orderId: "CM9810",
      user: {
        name: "Morgan Wilson",
        avatarUrl: "https://example.com/avatars/morganwilson.jpg",
      },
      project: "Product Photography",
      address: "202 Birch Blvd, Btown",
      date: "4 days ago",
      status: "Rejected",
    },
    {
      orderId: "CM9811",
      user: {
        name: "Jordan Brown",
        avatarUrl: "https://example.com/avatars/jordanbrown.jpg",
      },
      project: "Social Media Campaign",
      address: "303 Cedar Dr, Cville",
      date: "1 week ago",
      status: "In Progress",
    },
    {
      orderId: "CM9812",
      user: {
        name: "Casey White",
        avatarUrl: "https://example.com/avatars/caseywhite.jpg",
      },
      project: "SaaS Platform Development",
      address: "404 Elm St, Dcity",
      date: "2 weeks ago",
      status: "Complete",
    },
    {
      orderId: "CM9813",
      user: {
        name: "Drew Evans",
        avatarUrl: "https://example.com/avatars/drewevans.jpg",
      },
      project: "Data Analytics Report",
      address: "505 Fir Ave, Eburg",
      date: "3 weeks ago",
      status: "Pending",
    },
    {
      orderId: "CM9814",
      user: {
        name: "Jamie Lee",
        avatarUrl: "https://example.com/avatars/jamielee.jpg",
      },
      project: "Video Production",
      address: "606 Spruce Rd, Ftown",
      date: "1 month ago",
      status: "Approved",
    },
    {
      orderId: "CM9815",
      user: {
        name: "Pat Green",
        avatarUrl: "https://example.com/avatars/patgreen.jpg",
      },
      project: "Market Research",
      address: "707 Hemlock Dr, Gburg",
      date: "2 months ago",
      status: "Rejected",
    },
    {
      orderId: "CM9816",
      user: {
        name: "Ryan Scott",
        avatarUrl: "https://example.com/avatars/ryanscott.jpg",
      },
      project: "SEO Optimization",
      address: "808 Aspen St, Htown",
      date: "3 months ago",
      status: "In Progress",
    },
    {
      orderId: "CM9817",
      user: {
        name: "Cameron Ross",
        avatarUrl: "https://example.com/avatars/cameronross.jpg",
      },
      project: "Content Strategy",
      address: "909 Larch Ln, Icity",
      date: "4 months ago",
      status: "Complete",
    },
    {
      orderId: "CM9818",
      user: {
        name: "Dylan Baker",
        avatarUrl: "https://example.com/avatars/dylanbaker.jpg",
      },
      project: "Email Marketing",
      address: "111 Poplar Rd, Jville",
      date: "5 months ago",
      status: "Pending",
    },
    {
      orderId: "CM9819",
      user: {
        name: "Hayden King",
        avatarUrl: "https://example.com/avatars/haydenking.jpg",
      },
      project: "Corporate Branding",
      address: "222 Willow Dr, Ktown",
      date: "6 months ago",
      status: "Approved",
    },
    {
      orderId: "CM9820",
      user: {
        name: "Jesse Cooper",
        avatarUrl: "https://example.com/avatars/jessecooper.jpg",
      },
      project: "Webinar Production",
      address: "333 Sycamore St, Lville",
      date: "7 months ago",
      status: "Rejected",
    },
    {
      orderId: "CM9821",
      user: {
        name: "Jordan Foster",
        avatarUrl: "https://example.com/avatars/jordanfoster.jpg",
      },
      project: "Online Course Creation",
      address: "444 Cherry Ave, Mtown",
      date: "8 months ago",
      status: "In Progress",
    },
    {
      orderId: "CM9822",
      user: {
        name: "Quinn Carter",
        avatarUrl: "https://example.com/avatars/quinncarter.jpg",
      },
      project: "Podcast Editing",
      address: "555 Walnut Ln, Ncity",
      date: "9 months ago",
      status: "Complete",
    },
    {
      orderId: "CM9823",
      user: {
        name: "Robin Hughes",
        avatarUrl: "https://example.com/avatars/robinhughes.jpg",
      },
      project: "Brochure Design",
      address: "666 Chestnut Rd, Oville",
      date: "10 months ago",
      status: "Pending",
    },
    {
      orderId: "CM9824",
      user: {
        name: "Samira Turner",
        avatarUrl: "https://example.com/avatars/samiraturner.jpg",
      },
      project: "Infographic Creation",
      address: "777 Hickory Dr, Ptown",
      date: "11 months ago",
      status: "Approved",
    },
    {
      orderId: "CM9825",
      user: {
        name: "Terry Adams",
        avatarUrl: "https://example.com/avatars/terryadams.jpg",
      },
      project: "Business Card Design",
      address: "888 Ash St, Qcity",
      date: "1 year ago",
      status: "Rejected",
    },
    {
      orderId: "CM9826",
      user: {
        name: "Tony Lewis",
        avatarUrl: "https://example.com/avatars/tonylewis.jpg",
      },
      project: "Press Release Writing",
      address: "999 Pine Ln, Rville",
      date: "2 years ago",
      status: "In Progress",
    },
    {
      orderId: "CM9827",
      user: {
        name: "Valerie Clark",
        avatarUrl: "https://example.com/avatars/valerieclark.jpg",
      },
      project: "Annual Report Layout",
      address: "123 Juniper Rd, Stown",
      date: "3 years ago",
      status: "Complete",
    },
    {
      orderId: "CM9828",
      user: {
        name: "Will Evans",
        avatarUrl: "https://example.com/avatars/willevans.jpg",
      },
      project: "Newsletter Design",
      address: "456 Magnolia Dr, Tcity",
      date: "4 years ago",
      status: "Pending",
    },
    {
      orderId: "CM9829",
      user: {
        name: "Xavier Hall",
        avatarUrl: "https://example.com/avatars/xavierhall.jpg",
      },
      project: "Digital Ad Campaign",
      address: "789 Redwood St, Uville",
      date: "5 years ago",
      status: "Approved",
    },
    {
      orderId: "CM9830",
      user: {
        name: "Yasmine Green",
        avatarUrl: "https://example.com/avatars/yasminegreen.jpg",
      },
      project: "Customer Survey",
      address: "101 Sequoia Ave, Vtown",
      date: "6 years ago",
      status: "Rejected",
    },
    {
      orderId: "CM9831",
      user: {
        name: "Zane Harris",
        avatarUrl: "https://example.com/avatars/zaneharris.jpg",
      },
      project: "User Onboarding Flow",
      address: "202 Birch Blvd, Wcity",
      date: "7 years ago",
      status: "In Progress",
    },
    {
      orderId: "CM9832",
      user: {
        name: "Ava King",
        avatarUrl: "https://example.com/avatars/avaking.jpg",
      },
      project: "App Store Optimization",
      address: "303 Cherry Dr, Xville",
      date: "8 years ago",
      status: "Complete",
    },
    {
      orderId: "CM9833",
      user: {
        name: "Benjamin Lewis",
        avatarUrl: "https://example.com/avatars/benjaminlewis.jpg",
      },
      project: "Case Study Writing",
      address: "404 Elm St, Ytown",
      date: "9 years ago",
      status: "Pending",
    },
    {
      orderId: "CM9834",
      user: {
        name: "Chloe Moore",
        avatarUrl: "https://example.com/avatars/chloemoore.jpg",
      },
      project: "White Paper Design",
      address: "505 Fir Ave, Zcity",
      date: "10 years ago",
      status: "Approved",
    },
    {
      orderId: "CM9835",
      user: {
        name: "Daniel Nelson",
        avatarUrl: "https://example.com/avatars/danielnelson.jpg",
      },
      project: "Press Kit Creation",
      address: "606 Spruce Rd, Aville",
      date: "11 years ago",
      status: "Rejected",
    },
    {
      orderId: "CM9836",
      user: {
        name: "Ella O'Connor",
        avatarUrl: "https://example.com/avatars/ellaoconnor.jpg",
      },
      project: "Website Re-design",
      address: "707 Hemlock Dr, Btown",
      date: "12 years ago",
      status: "In Progress",
    },
    {
      orderId: "CM9837",
      user: {
        name: "Finn Parker",
        avatarUrl: "https://example.com/avatars/finnparker.jpg",
      },
      project: "Mobile Game Development",
      address: "808 Aspen St, Ccity",
      date: "13 years ago",
      status: "Complete",
    },
    {
      orderId: "CM9838",
      user: {
        name: "Grace Quinn",
        avatarUrl: "https://example.com/avatars/gracequinn.jpg",
      },
      project: "AI Integration",
      address: "909 Larch Ln, Dville",
      date: "14 years ago",
      status: "Pending",
    },
    {
      orderId: "CM9839",
      user: {
        name: "Henry Roberts",
        avatarUrl: "https://example.com/avatars/henryroberts.jpg",
      },
      project: "Blockchain Solution",
      address: "111 Poplar Rd, Etown",
      date: "15 years ago",
      status: "Approved",
    },
    {
      orderId: "CM9840",
      user: {
        name: "Isla Scott",
        avatarUrl: "https://example.com/avatars/islascott.jpg",
      },
      project: "IoT Device Prototype",
      address: "222 Willow Dr, Fcity",
      date: "16 years ago",
      status: "Rejected",
    },
    {
      orderId: "CM9841",
      user: {
        name: "Jack Turner",
        avatarUrl: "https://example.com/avatars/jackturner.jpg",
      },
      project: "Virtual Reality Experience",
      address: "333 Sycamore St, Gville",
      date: "17 years ago",
      status: "In Progress",
    },
    {
      orderId: "CM9842",
      user: {
        name: "Kara Underwood",
        avatarUrl: "https://example.com/avatars/karaunderwood.jpg",
      },
      project: "Augmented Reality App",
      address: "444 Cherry Ave, Htown",
      date: "18 years ago",
      status: "Complete",
    },
    {
      orderId: "CM9843",
      user: {
        name: "Leo Vance",
        avatarUrl: "https://example.com/avatars/leovance.jpg",
      },
      project: "Smart Home Integration",
      address: "555 Walnut Ln, Icity",
      date: "19 years ago",
      status: "Pending",
    },
    {
      orderId: "CM9844",
      user: {
        name: "Mia Walker",
        avatarUrl: "https://example.com/avatars/miawalker.jpg",
      },
      project: "Wearable Tech Development",
      address: "666 Chestnut Rd, Jville",
      date: "20 years ago",
      status: "Approved",
    },
    {
      orderId: "CM9845",
      user: {
        name: "Noah Yang",
        avatarUrl: "https://example.com/avatars/noahyang.jpg",
      },
      project: "Drone Software",
      address: "777 Hickory Dr, Ktown",
      date: "21 years ago",
      status: "Rejected",
    },
    {
      orderId: "CM9846",
      user: {
        name: "Olivia Zimmerman",
        avatarUrl: "https://example.com/avatars/oliviazimmerman.jpg",
      },
      project: "3D Printing Service",
      address: "888 Ash St, Lcity",
      date: "22 years ago",
      status: "In Progress",
    },
    {
      orderId: "CM9847",
      user: {
        name: "Peter Adams",
        avatarUrl: "https://example.com/avatars/peteradams.jpg",
      },
      project: "Robotics Engineering",
      address: "999 Pine Ln, Mville",
      date: "23 years ago",
      status: "Complete",
    },
    {
      orderId: "CM9848",
      user: {
        name: "Quinn Brooks",
        avatarUrl: "https://example.com/avatars/quinnbrooks.jpg",
      },
      project: "Biometric Security System",
      address: "123 Juniper Rd, Ntown",
      date: "24 years ago",
      status: "Pending",
    },
    {
      orderId: "CM9849",
      user: {
        name: "Rachel Carter",
        avatarUrl: "https://example.com/avatars/rachelcarter.jpg",
      },
      project: "Quantum Computing Research",
      address: "456 Magnolia Dr, Ocity",
      date: "25 years ago",
      status: "Approved",
    },
    {
      orderId: "CM9850",
      user: {
        name: "Samuel Davis",
        avatarUrl: "https://example.com/avatars/samueldavis.jpg",
      },
      project: "Cybersecurity Audit",
      address: "789 Redwood St, Pville",
      date: "26 years ago",
      status: "Rejected",
    },
  ],
};
